apiVersion: v1
kind: Service
metadata:
  name: wordsmith-db-svc
  labels:
    app: wordsmith-db-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: wordsmithdbport
  selector:
    app: wordsmith-db-label
  clusterIP: None