apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-web-deploy
  labels:
    app: wordsmith-web-deploy
spec:
  selector:
    matchLabels:
      app: wordsmith-web-label
  template:
    metadata:
      labels:
        app: wordsmith-web-label
    spec:
      containers:
        - name: wordsmith-web-container
          image: elyhamza/wordsmith-web
          env:
            - name: WORDSMITH_API_SERVICE
              value: wordsmith-api-svc
          ports:
            - containerPort: 80
              name: wswebport